export enum CanadianProvinces {
  Alberta = 'Alberta',
  BritishColumbia = 'British Columbia',
  Manitoba = 'Manitoba',
  NewBrunswick = 'New Brunswick',
  NewfoundlandAndLabrador = 'Newfoundland and Labrador',
  NovaScotia = 'Nova Scotia',
  Ontario = 'Ontario',
  PrinceEdwardIsland = 'Prince Edward Island',
  Quebec = 'Quebec',
  Saskatchewan = 'Saskatchewan',
  NorthwestTerritories = 'Northwest Territories',
  Nunavut = 'Nunavut',
  Yukon = 'Yukon',
}
